title: Writing in Emacs
description: Share emacs tricks
author: llcc
github: https://github.com/llcc
about: An amateur in Emacs, but with enthusiastic
urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/llcc
    - text: XML Feed
      url: /feed.xml
url: "https://layatjpy.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown