# Site settings
title: "Leu Grady"
email: lzhes43@gmail.com
description: "A blog for Leu Grady."
baseurl: ""
url: "http://llcc.github.io/layatjpy/"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: "UA-20365477-4"
disqus_account: leu_grady
github_repository: https://github.com/llcc/layatjpy
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: Leu_Grady
github_username:  llcc
stackoverflow_link: Leu_Grady

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/Leu_grady\">Leu Grady</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/llcc/layatjpy\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
