name: Leu Grady - Alloy Researcher
markdown: redcarpet
pygments: true
timezone: Asian/Japanese
permalink: /:title.html
baseurl: /layatjpy/
url: http://llcc.github.io
paginate: 5
paginate_path: 'page:num'

# Permalinksxs

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

github:
  repo:           https://github.com/llcc/layatjpy

