markdown: rdiscount
permalink: /:title/
url: "http://llcc.github.io/layatjpy"
baseurl: "http://llcc.github.io/layatjpy"
highlighter: pygments
name: 先空着
description: 先空着 | Stop talking, start doing.
author: llcc
duoshuo: niushuai
weibo: 1891858481
hub: llcc
safe: true
paginate: 100
about: "弱菜一枚。"
